import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Store() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Africa Herbal Center - Decouverte</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{height: "700px"}}>
          <h3 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Decouverte!</a>
          </h3>
        </div>

        
      </main>

      
    </div>
  )
}
