import Prismic from "prismic-javascript";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Client } from "../prismic-configuration.js";
import HeroSection from '../components/home/heroSection/Hero.js'
import PresentationSection from '../components/home/presentation/Presentation.js'

export default function Home({slides, presentation}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Africa Herbal Center - Accueil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeroSection slides={slides} />
        <PresentationSection information={presentation} />
        <div style={{height: "500px"}}>
        </div>

        
      </main>

      
    </div>
  )
}

export async function getStaticProps() {
  const slides0 = await Client().query(
    Prismic.Predicates.at("document.type", "slides")
  );
  const presentation0 =  await Client().query(
    Prismic.Predicates.at("document.type", "presentation")
  );

  const slides = slides0.results.map(slide => {
    const container = {};
    container['id'] = slide.id;
    container['title'] = slide.data.title[0].text;
    container['caption'] = slide.data.caption[0].text;
    container['picture'] = slide.data.picture.url;
    return container;
  })

  const presentation = presentation0.results.map(info => {
    const container = {};
    container['id'] = info.id;
    container['text'] = info.data.info;
    container['picture'] = info.data.picture.url;
    return container;
  })[0]
  //console.log(presentation);
  
  return {
    props: {
      slides,
      presentation,
    },
    revalidate: 10, // In seconds
  }
}
