import Prismic from "prismic-javascript";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HeroSection from '../components/home/heroSection/Hero.js'
import { Client } from "../prismic-configuration.js";


export default function Home({slides}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Africa Herbal Center - Accueil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeroSection slides={slides} />
        <div style={{height: "500px"}}>
                    
        </div>

        
      </main>

      
    </div>
  )
}

export async function getStaticProps() {
  const slides0 = await Client().query(
    Prismic.Predicates.at("document.type", "slides")
  );

  const slides = slides0.results.map(slide => {
    const container = {};
    container['id'] = slide.id;
    container['title'] = slide.data.title[0].text;
    container['caption'] = slide.data.caption[0].text;
    container['picture'] = slide.data.picture.url;
    return container;
  })
  console.log(slides);
  
  return {
    props: {
      slides,
    },
    revalidate: 10, // In seconds
  }
}
