import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import Prismic from "prismic-javascript";
import { Client } from "../prismic-configuration.js";

import CoverSection from '../components/cover/Cover.js'
import ProductRowSection from '../components/products/ProductRow.js'


export default function Blog({coverPicture, products}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Africa Herbal Center - Pharmacopée</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CoverSection imageData={coverPicture}/>
        <ProductRowSection products={products} />
        <div style={{height: "200px"}}>
        </div>        
      </main>      
    </div>
  )
}

export async function getStaticProps() {
  const coverPicture0 = await Client().query(
    Prismic.Predicates.at("document.type", "store_cover")
  );
  const products0 = await Client().query(
    Prismic.Predicates.at("document.type", "product")
  );

  const coverPicture = coverPicture0.results.map(info => {
    const container = {};
    container['id'] = info.id;
    container['url'] = info.data.picture.url;
    return container;
  })[0] 

  const products = products0.results.slice(0, 3).map(info => {
    const container = {};
    container['id'] = info.id;
    container['name'] = info.data.name;
    container['picture'] = info.data.picture.url;
    container['category'] = info.data.category;
    container['price'] = info.data.price;
    container['slug'] = info.slugs[0];
    container['description'] = info.data.description;
    return container;
  }) 

  //console.log(coverPicture);
  
  return {
    props: {
      coverPicture,
      products,
    },
    revalidate: 10, // In seconds
  }
}

